# Generated by Django 4.2.17 on 2025-06-01 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "inn",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                10, "INN can't be shorter than 10"
                            )
                        ],
                        verbose_name="ИНН",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
