# Generated by Django 4.2.17 on 2025-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="inn",
            field=models.CharField(
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                verbose_name="ИНН",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("inn__length", 10), ("inn__length", 12), _connector="OR"
                ),
                name="inn_length",
            ),
        ),
    ]
